# Generated by Django 6.0.1 on 2026-01-22 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='問題を簡潔に説明するタイトルを入力してください', max_length=200, verbose_name='問題のタイトル')),
                ('description', models.TextField(help_text='問題の詳細な説明を入力してください', verbose_name='問題の詳細説明')),
                ('image', models.ImageField(blank=True, help_text='問題に関連する画像をアップロードしてください（オプション）', upload_to='problems/', verbose_name='問題の画像')),
                ('category', models.CharField(help_text='例：一次方程式、二次関数、確率など', max_length=100, verbose_name='単元名')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='問題が投稿された日時（自動で記録される）', verbose_name='投稿日時')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='問題が最後に更新された日時（自動で更新される）', verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '数学の問題',
                'verbose_name_plural': '数学の問題',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.IntegerField(choices=[(0, '方針'), (1, '公式'), (2, 'コツ')], default=0, help_text='0:方針、1:公式、2:コツ から選択', verbose_name='ヒントの種類')),
                ('content', models.TextField(help_text='具体的なヒント内容を入力してください', verbose_name='ヒントの内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='math_app.problem', verbose_name='関連する問題')),
            ],
            options={
                'verbose_name': 'ヒント',
                'verbose_name_plural': 'ヒント',
                'ordering': ['problem', 'stage_type', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['user', '-created_at'], name='math_app_pr_user_id_7d2a6e_idx'),
        ),
    ]
