# Generated by Django 6.0.1 on 2026-01-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.CharField(help_text='例：確率、三角関数、微分など', max_length=100, verbose_name='単元名'),
        ),
    ]
