# Generated by Django 5.2.8 on 2026-02-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0002_alter_problem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例：二次関数、確率、三角関数など', max_length=50, unique=True, verbose_name='単元タグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '単元タグ',
                'verbose_name_plural': '単元タグ',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='problem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='description',
        ),
        migrations.AddField(
            model_name='problem',
            name='hint_approach',
            field=models.TextField(blank=True, help_text='問題を解くための方針や方向性を記入してください', verbose_name='方針'),
        ),
        migrations.AddField(
            model_name='problem',
            name='hint_formula',
            field=models.TextField(blank=True, help_text='使用すべき公式や定理を記入してください', verbose_name='公式'),
        ),
        migrations.AddField(
            model_name='problem',
            name='hint_technique',
            field=models.TextField(blank=True, help_text='計算や考え方のコツを記入してください', verbose_name='コツ'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='content',
            field=models.TextField(verbose_name='ヒントの内容'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='stage_type',
            field=models.IntegerField(choices=[(0, '方針'), (1, '公式'), (2, 'コツ')], default=0, verbose_name='ヒントの種類'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='image',
            field=models.ImageField(help_text='問題の画像をアップロードしてください', upload_to='problems/', verbose_name='問題の画像'),
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(help_text='該当する単元タグを選択してください', related_name='problems', to='math_app.tag', verbose_name='単元タグ'),
        ),
    ]
