# Generated by Django 5.2.8 on 2026-02-04 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0003_tag_remove_problem_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('junior1', '中学1年'), ('junior2', '中学2年'), ('junior3', '中学3年'), ('high1', '高校1年'), ('high2', '高校2年'), ('high3', '高校3年')], max_length=10, unique=True, verbose_name='学年コード')),
                ('name', models.CharField(help_text='例：中1, 高2など', max_length=20, verbose_name='学年名')),
                ('order', models.IntegerField(default=0, verbose_name='表示順序')),
            ],
            options={
                'verbose_name': '学年',
                'verbose_name_plural': '学年',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['grade', 'name'], 'verbose_name': '単元タグ', 'verbose_name_plural': '単元タグ'},
        ),
        migrations.AlterField(
            model_name='problem',
            name='image',
            field=models.ImageField(blank=True, help_text='問題の画像をアップロードしてください（手書きの場合、手書き画像を画像として保存できます）', null=True, upload_to='problems/', verbose_name='問題の画像'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='例：二次関数、確率、三角関数など', max_length=50, verbose_name='単元タグ'),
        ),
        migrations.AddField(
            model_name='problem',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='math_app.grade', verbose_name='学年'),
        ),
        migrations.AddField(
            model_name='tag',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='math_app.grade', verbose_name='学年'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'grade')},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='math_app.grade', verbose_name='学年')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザープロフィール',
                'verbose_name_plural': 'ユーザープロフィール',
            },
        ),
    ]
