# Generated by Django 5.2.8 on 2026-02-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0004_grade_alter_tag_options_alter_problem_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['grade', 'order', 'name'], 'verbose_name': '単元タグ', 'verbose_name_plural': '単元タグ'},
        ),
        migrations.AddField(
            model_name='tag',
            name='order',
            field=models.IntegerField(default=0, help_text='小さい数から大きい数の順に表示されます', verbose_name='習う順番'),
        ),
    ]
