# Generated by Django 5.2.8 on 2026-02-04 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0005_alter_tag_options_tag_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例：数1, 数A, 数2など', max_length=50, verbose_name='科目名')),
                ('code', models.CharField(help_text='例：math1, mathA など', max_length=10, unique=True, verbose_name='科目コード')),
                ('order', models.IntegerField(default=0, verbose_name='表示順序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('grade', models.ForeignKey(help_text='この科目が対応する学年（高1, 高2, 高3）', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='math_app.grade', verbose_name='学年')),
            ],
            options={
                'verbose_name': '科目',
                'verbose_name_plural': '科目',
                'ordering': ['grade', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='高校の科目（高1～高3のみ）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='math_app.subject', verbose_name='科目'),
        ),
    ]
