# Generated by Django 5.2.8 on 2026-02-04 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0006_subject_tag_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
    ]
