# Generated by Django 5.2.8 on 2026-02-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0007_remove_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='hint_approach_image',
            field=models.ImageField(blank=True, help_text='図や表などの画像をアップロードしてください', null=True, upload_to='hints/approach/', verbose_name='方針の画像'),
        ),
        migrations.AddField(
            model_name='problem',
            name='hint_formula_image',
            field=models.ImageField(blank=True, help_text='公式や計算過程の画像をアップロードしてください', null=True, upload_to='hints/formula/', verbose_name='公式の画像'),
        ),
        migrations.AddField(
            model_name='problem',
            name='hint_technique_image',
            field=models.ImageField(blank=True, help_text='重要なポイントの画像をアップロードしてください', null=True, upload_to='hints/technique/', verbose_name='注意点の画像'),
        ),
    ]
