# Generated by Django 5.2.8 on 2026-02-15 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0008_problem_hint_approach_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='返信用メールアドレス')),
                ('subject', models.CharField(max_length=200, verbose_name='件名')),
                ('message', models.TextField(verbose_name='質問内容')),
                ('problem_image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='問題画像（任意）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('is_replied', models.BooleanField(default=False, verbose_name='返信済み')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='質問者')),
            ],
            options={
                'verbose_name': '質問',
                'verbose_name_plural': '質問',
                'ordering': ['-created_at'],
            },
        ),
    ]
